// Your code goes here
let headerBar = document.querySelector('.nav-container')
console.log(headerBar)
let headerText = document.querySelector('.logo-heading')
console.log(headerText)
let navBarList = document.querySelector('.nav')
console.log(navBarList)
let navItems = document.querySelectorAll('.nav-link')
console.log(navItems)

let fullContainer = document.querySelector('.home')
console.log(fullContainer)

let intro = document.querySelector('.intro')
console.log(intro)
let introImg = document.querySelector('.intro img')
console.log(introImg)
let introHead = document.querySelector('.intro h2')
console.log(introHead)
let introText = document.querySelector('.intro p')
console.log(introText)

let content = document.querySelector('.content-section')
console.log(content)
let contentAllText = document.querySelector('.text-content')
console.log(contentAllText)
let contentHeadText = document.querySelector('.text-content h2')
console.log(contentHeadText)
let contentP1Text = document.querySelector('.text-content p')
console.log(contentP1Text)
let contentP2Text = document.querySelector('.text-content p')
console.log(contentP2Text)
