let redBox = document.querySelector('.block--red')
let blueBox = document.querySelector('.block--blue')
let greenBox = document.querySelector('.block--green')
let pinkBox = document.querySelector('.block--pink')
let grayBox = document.querySelector('.block--gray')
